{{- if .Values.awsAdapter.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno-aws-adapter.name" . }}-installer
  namespace: {{ include "kyverno-aws-adapter.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kyverno-aws-adapter.name" . }}-installer
subjects:
- kind: ServiceAccount
  name: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
{{- end }}
