{{- if and (eq .Values.kyverno.rbac.create true) (contains "v1.8" .Values.kyverno.image.tag) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace:  {{ include "kyverno.namespace" . }}
  name: {{ include "kyverno18.name" . }}-installer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}
