{{- if .Values.cisAdapter.rbac.create }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "kube-bench.labels" . | nindent 4 }}
  name: {{ include "kube-bench.namespace" . }}
{{- end }}
