{{- if .Values.cisAdapter.createCR }}
apiVersion: security.nirmata.io/v1alpha1
kind: KyvernoAdapter
metadata:
  annotations:
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
  name: cis-adapter-config
  namespace: {{ template "enterprise-kyverno.namespace" . }}
spec:
  adapterType: CIS
  namespace: {{ include "kube-bench.namespace" . }}
  repository: {{ .Values.cisAdapter.image.repository }}
  version: {{ .Values.cisAdapter.image.tag }}
  replicas: {{ .Values.cisAdapter.replicas }}

  helm:
    values:
      {{- toYaml .Values.cisAdapter.helm | nindent 6 }}
      fullnameOverride: {{ .Values.cisAdapter.fullnameOverride }}
      nameOverride: {{ .Values.cisAdapter.nameOverride }}
{{- end }}
