{{ range $pol := include "enterprise-kyverno.enabledPolicysets" . | split "," }}

{{- $psetName := "invalid" -}}
{{- $psetType := "" -}}
{{- $chartRepo := "" -}}
{{- $chartName := "" -}}
{{- $version := "" -}}

{{- if eq $pol "best-practices" -}}
  {{- $psetName = "best-practices" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-charts" -}}
  {{- $chartName = "best-practice-policies" -}}
  {{- $version = "0.1.1" -}}
{{- else if eq $pol "pod-security" -}}
  {{- $psetName = "pod-security" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-charts" -}}
  {{- $chartName = "pod-security-policies" -}}
  {{- $version = "0.1.0" -}}
{{- else if eq $pol "rbac-best-practices" -}}
  {{- $psetName = "rbac-best-practices" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-charts" -}}
  {{- $chartName = "rbac-best-practice-policies" -}}
  {{- $version = "0.1.0" -}}
{{- end -}}

{{- if ne $psetName "invalid" -}}
---
apiVersion: security.nirmata.io/v1alpha1
kind: PolicySet
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: policyset
    app.kubernetes.io/instance: {{ $psetName }}
    app.kubernetes.io/part-of: enterprise-kyverno-operator
  name: {{ $psetName }}
  namespace: {{ template "enterprise-kyverno.namespace" $ }}
spec:
  {{ if eq $psetType "helm" }}
  source:
    helm:
      chartRepo: {{ $chartRepo }}
      chartName: {{ $chartName }}
      version: {{ $version }}
  {{ end }}

{{ end }}
{{ end }}
