{{- if .Values.image.pullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "enterprise-kyverno.labels" $ | nindent 4 }}
    app: enterprise-kyverno
  name: image-pull-secret
  namespace: {{ include "enterprise-kyverno.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
