apiVersion: v1
kind: Secret
metadata:
  name: operator-params
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
    app: enterprise-kyverno
type: Opaque
data:
  licenseKey: {{ required "License key is required" .Values.licenseKey | b64enc }}
  {{- if .Values.apiKey }}
  apiKey: {{ .Values.apiKey | b64enc }}
  {{- end }}
