apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "enterprise-kyverno.fullname" . }}-operator-cleanup
  namespace: {{ template "enterprise-kyverno.namespace" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "enterprise-kyverno.name" . }}-operator
{{ include "enterprise-kyverno.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "enterprise-kyverno.fullname" . }}-operator-cleanup
      labels:
        app: {{ template "enterprise-kyverno.name" . }}-operator
{{ include "enterprise-kyverno.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kubectl
          image: k8s.gcr.io/hyperkube:v1.16.12
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - >
              for i in {{ include "enterprise-kyverno.policysets" . }}; 
              do 
                kubectl -n {{ include "enterprise-kyverno.namespace" . }} delete PolicySet $i;
              done;
              {{- if .Values.awsAdapter.createCR }}
              kubectl -n {{ include "enterprise-kyverno.namespace" . }} delete kyvernoadapters aws-adapter-config;
              {{- end }}
              {{- if .Values.kyverno.createCR }}
              kubectl -n {{ include "enterprise-kyverno.namespace" . }} delete kyvernoes kyverno;
              sleep 10;
              {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            limits:
              memory: 128Mi
      restartPolicy: OnFailure
