{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "enterprise-kyverno.fullname" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace:  {{ include "enterprise-kyverno.namespace" . }}
  name: {{ include "enterprise-kyverno.fullname" . }}-installer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}
