{{- if and (eq .Values.enableWebhook true) (eq .Values.certManager "operator") }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
    "cert.security.nirmata.io/managed-by": "kyverno-operator"
    app: enterprise-kyverno-operator
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
  ca.crt: ""
{{- end }}
