{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "image-scan-adapter.fullname" . }}
  labels:
    {{- include "image-scan-adapter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
- apiGroups:
  - kyverno.io
  resources:
  - clusterpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - kyverno.io
  resources:
  - policies
  verbs:
  - list
  - watch
- apiGroups:
  - security.nirmata.io
  resources:
  - imagescanadapterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.nirmata.io
  resources:
  - imagescanadapterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - security.nirmata.io
  resources:
  - imagescanadapterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - create
  - get
  - update
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "image-scan-adapter.serviceAccountName" . }}
  labels:
    {{- include "image-scan-adapter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "image-scan-adapter.fullname" . }}
  labels:
    {{- include "image-scan-adapter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "image-scan-adapter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "image-scan-adapter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

