apiVersion: security.nirmata.io/v1alpha1
kind: ImageScanAdapterConfig
metadata:
  name: {{ include "image-scan-adapter.fullname" . }}
  labels:
    {{- include "image-scan-adapter.labels" . | nindent 4 }}
spec:
  {{- if .Values.severity }}
  severity: 
    {{- range $val := .Values.severity }}
      - {{ $val }}
    {{- end }}
  {{- end }}
  policyReportPrefix: {{ .Values.policyReportPrefix }}
  scannerEngine: {{ .Values.scannerEngine }}
  outputFormat: {{ .Values.outputFormat }}
  scanInterval: {{ .Values.scanInterval }}
  scanAll: {{ .Values.scanAll }}
  selectors:
    {{- if .Values.selectors.namespaces }}
    namespaces: 
      {{- range $val := .Values.selectors.namespaces }}
        - {{ $val }}
      {{- end }}
    {{- end }}
