apiVersion: v1
name: kyverno-chart
version: v1.11.3-02-aws
appVersion: v1.9.5
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Native Policy Management
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - policy engine
  - validating webhook
  - admissions controller
home: https://kyverno.io/
sources:
  - https://github.com/kyverno/kyverno
maintainers:
  - name: Nirmata
    url: https://kyverno.io/
engine: gotpl
kubeVersion: ">=1.20.0-0"
