apiVersion: v1
name: kyverno-chart
version: v1.10.0-05-aws
appVersion: v1.8.3
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Native Policy Management
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - validating webhook
  - admissions controller
home: https://kyverno.io/
sources:
  - https://github.com/kyverno/kyverno
maintainers:
  - name: Nirmata
    url: https://kyverno.io/
engine: gotpl
kubeVersion: ">=1.16.0-0"
