# Default values for kube-bench.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # --image repository of kube-bench-adapter
  repository: ghcr.io/nirmata/kube-bench-adapter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
   # --tag of image repository of kube-bench-adapter
  tag: "v0.2.0"
  pullSecrets:
    registry:
    # Leave blank, if no ImagePullSecret is needed.
    name:
    # If set to false, the gerrit-master chart expects either a ImagePullSecret
    # with the name configured above to be present on the cluster or that no
    # credentials are needed.
    create: false
    username:
    password:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  create: true

cronjob:
  # -- cronjob schedule, default is weekly.
  schedule: '"@weekly"'

kubeBench:
  command: "policyreport"
  # -- name of kube-bench adapter cluster policy report
  name: "kube-bench"
  # -- category of the policy report
  category: "CIS Benchmarks"
  # -- specifies namespace where kube-bench job will run
  namespace: "default"
  # -- kube-bench image used for the adapter
  kubebenchImg: "aquasec/kube-bench:v0.6.6"
  # -- absolute path to the kubeconfig file
  kubeconfig: "$HOME/.kube/config"
  # -- targets for benchmark of kube-bench job
  kubeBenchTargets: "master,node,etcd,policies"
  # -- name of provider of YAML for kube-bench job, allowed values: job.yaml, job-master.yaml, job-node.yaml, job-ack.yaml, job-aks.yaml, job-eks-asff.yaml, job-eks.yaml, job-gke.yaml, job-iks.yaml
  yaml: "job.yaml"

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 80
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 200Mi

## Liveness Probe. The block is directly forwarded into the deployment, so you can use whatever livenessProbe configuration you want.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  exec:
    command:
    - cat
    - run.sh

## Readiness Probe. The block is directly forwarded into the deployment, so you can use whatever readinessProbe configuration you want.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  exec:
    command:
    - cat
    - run.sh

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
