{{ if and .Values.image.pullSecrets.name .Values.image.pullSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecrets.name }}
  namespace: {{ template "kyverno.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
