{{- if and (eq .Values.rbac.create true) (eq .Values.rbac.serviceAccount.create true)}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyverno.serviceAccountName" . }}
  labels:
    {{- include "kyverno.labels" . | nindent 4 }}
    app: kyverno
  {{- if .Values.rbac.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ template "kyverno.namespace" . }}
{{- end }}
