apiVersion: v2
type: application
name: kyverno
version: 1.6.7
appVersion: v1.9.3-n4k.nirmata.1
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Native Policy Management
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - policy engine
  - validating webhook
  - admissions controller
home: https://kyverno.io/
sources:
  - https://github.com/kyverno/kyverno
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Documentation
      url: https://kyverno.io/docs
  # valid kinds are: added, changed, deprecated, removed, fixed and security
  artifacthub.io/changes: |
    - kind: added
      description: support for webhook annotations in config map
