apiVersion: v2
name: kyverno
version: v1.5.1
appVersion: v1.8.1-n4kbuild.1
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Native Policy Management
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - policy engine
  - validating webhook
  - admissions controller
home: https://kyverno.io/
sources:
  - https://github.com/kyverno/kyverno
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
engine: gotpl
kubeVersion: ">=1.16.0-0"