{{- if and (eq .Values.kyverno.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (eq .Values.kyverno.majorVersion "1.9") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.fullname" . }}
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      {{- include "kyverno19.matchLabels" . | nindent 6 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.fullname" . }}:userinfo
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - clusterroles
  - rolebindings
  - clusterrolebindings
  verbs:
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.fullname" . }}:policies
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
rules:
- apiGroups:
    - kyverno.io
  resources:
    - policies
    - policies/status
    - clusterpolicies
    - clusterpolicies/status
    - generaterequests
    - generaterequests/status
    - updaterequests
    - updaterequests/status
    - admissionreports
    - clusteradmissionreports
    - backgroundscanreports
    - clusterbackgroundscanreports
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    - deletecollection
- apiGroups:
    - wgpolicyk8s.io
  resources:
    - policyreports
    - policyreports/status
    - clusterpolicyreports
    - clusterpolicyreports/status
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.fullname" . }}:view
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.fullname" . }}:generate
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
      - networkpolicies
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - namespaces
      - configmaps
      - secrets
      - resourcequotas
      - limitranges
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - update
      - patch
      - delete
  {{- if .Values.kyverno.generatecontrollerExtraResources }}
  - apiGroups:
      - '*'
    resources:
    {{- range .Values.kyverno.generatecontrollerExtraResources }}
      - {{ . }}
    {{- end }}
    verbs:
      - create
      - update
      - delete
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.fullname" . }}:events
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
rules:
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.fullname" . }}:webhook
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
{{- end }}
