{{- if and (eq .Values.kyverno.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.9" .Values.kyverno.image.tag) -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno19.fullname" . }}
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kyverno19.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kyverno19.serviceAccountName" . }}
  namespace: {{ template "kyverno.namespace" . }}
{{- end -}}
