{{- if and (eq .Values.kyverno.webhooksCleanup.enable true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.9" .Values.kyverno.image.tag) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kyverno19.fullname" . }}-hook-pre-delete
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
    app: kyverno
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccount: {{ template "kyverno19.serviceAccountName" . }}
      containers:
        - name: kubectl
          image: {{ .Values.kyverno.webhooksCleanup.image }}
          command:
            - sh
            - '-c'
            - >-
              kubectl delete validatingwebhookconfiguration -l webhook.kyverno.io/managed-by=kyverno;
              kubectl delete mutatingwebhookconfiguration -l webhook.kyverno.io/managed-by=kyverno;
      restartPolicy: Never
  backoffLimit: 2
{{- end }}