{{- if and (eq .Values.kyverno.rbac.create true) (eq .Values.kyverno.majorVersion "1.9") }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
  name: {{ include "kyverno.namespace" . }}
{{- end }}
