{{- if and (eq .Values.kyverno.rbac.create true) (eq .Values.kyverno.majorVersion "1.9") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace:  {{ include "kyverno.namespace" . }}
  name: {{ include "kyverno19.name" . }}-installer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}
