{{- if and (eq .Values.kyverno.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.8" .Values.kyverno.image.tag) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno18.fullname" . }}:admin-policies
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    app: kyverno
rules:
- apiGroups:
  - kyverno.io
  resources:
  - policies
  - clusterpolicies
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    app: kyverno
  name: {{ template "kyverno18.fullname" . }}:admin-policyreport
rules:
  - apiGroups:
      - wgpolicyk8s.io
    resources:
      - policyreports
      - clusterpolicyreports
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    app: kyverno
  name: {{ template "kyverno18.fullname" . }}:admin-reports
rules:
- apiGroups:
    - kyverno.io
  resources:
    - admissionreports
    - clusteradmissionreports
    - backgroundscanreports
    - clusterbackgroundscanreports
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    app: kyverno
  name: {{ template "kyverno18.fullname" . }}:admin-generaterequest
rules:
- apiGroups:
  - kyverno.io
  resources:
  - generaterequests
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    app: kyverno
  name: {{ template "kyverno18.fullname" . }}:admin-updaterequest
rules:
- apiGroups:
  - kyverno.io
  resources:
  - updaterequests
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
{{- end }}
