{{- if and (eq .Values.kyverno.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (eq .Values.kyverno.majorVersion "1.8") }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno18.fullname" . }}
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    app: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kyverno18.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kyverno18.serviceAccountName" . }}
  namespace: {{ template "kyverno.namespace" . }}
{{- end -}}
