{{- if and (eq .Values.kyverno.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.8" .Values.kyverno.image.tag)}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kyverno18.fullname" . }}:leaderelection
  namespace: {{ template "kyverno.namespace" . }}
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    app: kyverno
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - patch
  - update
# Allow update of Kyverno deployment annotations
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - patch
    - update
    - watch

{{- end }}
