{{- if and (eq .Values.kyverno.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.8" .Values.kyverno.image.tag) }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno18.fullname" . }}:leaderelection
  namespace: {{ template "kyverno.namespace" . }}
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    app: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kyverno18.fullname" . }}:leaderelection
subjects:
- kind: ServiceAccount
  name: {{ template "kyverno18.serviceAccountName" . }}
  namespace: {{ template "kyverno.namespace" . }}

{{- end }}
