{{- if and (eq .Values.kyverno.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.8" .Values.kyverno.image.tag) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyverno18.serviceAccountName" . }}
  labels: {{ include "kyverno18.labels" . | nindent 4 }}
    app: kyverno
  {{- if .Values.kyverno.rbac.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.kyverno.rbac.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ template "kyverno.namespace" . }}
{{- end }}
