{{- if .Values.cisAdapter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-bench.serviceAccountName" . }}
  labels:
    {{- include "kube-bench.labels" . | nindent 4 }}
  {{- with .Values.cisAdapter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace : {{.Values.cisAdapter.namespace}}
{{- end }}
