{{- if .Values.kyverno.cleanupController.enabled -}}
{{- if and (eq .Values.kyverno.cleanupController.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (eq .Values.kyverno.majorVersion "1.9") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.cleanup-controller.roleName" . }}
  labels:
    {{- include "kyverno19.cleanup-controller.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        {{- include "kyverno19.cleanup-controller.matchLabels" . | nindent 8 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.cleanup-controller.roleName" . }}:core
  labels:
    {{- include "kyverno19.cleanup-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kyverno.io
    resources:
      - clustercleanuppolicies
      - cleanuppolicies
      - clustercleanuppolicies/*
      - cleanuppolicies/*
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
{{- with .Values.kyverno.cleanupController.rbac.clusterRole.extraResources }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno19.cleanup-controller.roleName" $ }}:additional
  labels:
    {{- include "kyverno19.cleanup-controller.labels" $ | nindent 4 }}
rules:
  {{- range . }}
  - apiGroups:
      {{- toYaml .apiGroups | nindent 6 }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    verbs:
      - delete
      - list
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
