{{- if .Values.kyverno.cleanupController.enabled -}}
{{- if and (eq .Values.kyverno.cleanupController.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (eq .Values.kyverno.majorVersion "1.9") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno19.cleanup-controller.roleName" . }}
  labels:
    {{- include "kyverno19.cleanup-controller.labels" . | nindent 4 }}
  namespace: {{ template "kyverno.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kyverno19.cleanup-controller.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kyverno19.cleanup-controller.serviceAccountName" . }}
  namespace: {{ template "kyverno.namespace" . }}
{{- end -}}
{{- end -}}
