{{- if .Values.kyverno.cleanupController.enabled -}}
{{- if and (eq .Values.kyverno.cleanupController.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.9" .Values.kyverno.image.tag) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyverno19.cleanup-controller.serviceAccountName" . }}
  labels:
    {{- include "kyverno19.cleanup-controller.labels" . | nindent 4 }}
  namespace: {{ template "kyverno.namespace" . }}
{{- end -}}
{{- end -}}
