{{- if .Values.webhookEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kyverno-operator
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: kyverno-operator
  name: kyverno-operator-serving-cert
  namespace: {{ include "kyvernoMonitorNamespace" . }}
spec:
  dnsNames:
  - kyverno-operator-webhook-service.nirmata-kyverno-operator.svc
  - kyverno-operator-webhook-service.nirmata-kyverno-operator.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kyverno-operator-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kuberentes.io/name: issuer
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kyverno-operator
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kyverno-operator
  name: kyverno-operator-selfsigned-issuer
  namespace: {{ include "kyvernoMonitorNamespace" . }}
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: nirmata-kyverno-operator/kyverno-operator-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: kyverno-operator
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: kyverno-operator
  name: kyverno-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kyverno-operator-webhook-service
      namespace: {{ include "kyvernoMonitorNamespace" . }}
      path: /validate-security-nirmata-io-v1-kyvernooperator
  failurePolicy: Ignore
  name: vkyvernopolcpol.kb.io
  rules:
  - apiGroups:
    - kyverno.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusterpolicies
    - policies
  sideEffects: None
{{- end }}
