apiVersion: security.nirmata.io/v1
kind: KyvernoOperator
metadata:
  labels:
    app.kubernetes.io/name: kyvernooperator
    app.kubernetes.io/instance: kyvernooperator
    app.kubernetes.io/part-of: kyverno-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kyverno-operator
  name: kyvernooperator
  namespace: {{ include "kyvernoMonitorNamespace" . }}
spec:
# isRunning
  image: {{ .Values.validKyvernoImages }}
  pdbMinAvailable: 1
  pdbMaxUnavailable: 1
# isHA
  enableAntiAffinity: true
  minReplicas: 3
  minNodes: 2
