{{ if and .Values.imagePullSecret.name .Values.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ include "venafiAdapterNamespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretDockerConfig" . }}
{{- end }}
